name: sba_app
description: a social network to hire technicians and to get hired as one.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  provider: ^6.0.0
  intl: ^0.17.0
  uuid: ^3.0.4
  http: ^0.13.4
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^2.0.13
  url_launcher: ^6.0.10
  shared_preferences: ^2.0.7
  json_annotation: ^4.1.0
  cached_network_image: ^3.1.0
  flutter_slidable: ^0.6.0
  smooth_star_rating: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.1
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/